/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as graphql from "@nestjs/graphql";
import { GraphQLError } from "graphql";
import { isRecordNotFoundError } from "../../prisma.util";
import { MetaQueryPayload } from "../../util/MetaQueryPayload";
import * as nestAccessControl from "nest-access-control";
import * as gqlACGuard from "../../auth/gqlAC.guard";
import { GqlDefaultAuthGuard } from "../../auth/gqlDefaultAuth.guard";
import * as common from "@nestjs/common";
import { AclFilterResponseInterceptor } from "../../interceptors/aclFilterResponse.interceptor";
import { AclValidateRequestInterceptor } from "../../interceptors/aclValidateRequest.interceptor";
import { Leaderboard } from "./Leaderboard";
import { LeaderboardCountArgs } from "./LeaderboardCountArgs";
import { LeaderboardFindManyArgs } from "./LeaderboardFindManyArgs";
import { LeaderboardFindUniqueArgs } from "./LeaderboardFindUniqueArgs";
import { CreateLeaderboardArgs } from "./CreateLeaderboardArgs";
import { UpdateLeaderboardArgs } from "./UpdateLeaderboardArgs";
import { DeleteLeaderboardArgs } from "./DeleteLeaderboardArgs";
import { User } from "../../user/base/User";
import { LeaderboardService } from "../leaderboard.service";
@common.UseGuards(GqlDefaultAuthGuard, gqlACGuard.GqlACGuard)
@graphql.Resolver(() => Leaderboard)
export class LeaderboardResolverBase {
  constructor(
    protected readonly service: LeaderboardService,
    protected readonly rolesBuilder: nestAccessControl.RolesBuilder
  ) {}

  @graphql.Query(() => MetaQueryPayload)
  @nestAccessControl.UseRoles({
    resource: "Leaderboard",
    action: "read",
    possession: "any",
  })
  async _leaderboardsMeta(
    @graphql.Args() args: LeaderboardCountArgs
  ): Promise<MetaQueryPayload> {
    const result = await this.service.count(args);
    return {
      count: result,
    };
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @graphql.Query(() => [Leaderboard])
  @nestAccessControl.UseRoles({
    resource: "Leaderboard",
    action: "read",
    possession: "any",
  })
  async leaderboards(
    @graphql.Args() args: LeaderboardFindManyArgs
  ): Promise<Leaderboard[]> {
    return this.service.leaderboards(args);
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @graphql.Query(() => Leaderboard, { nullable: true })
  @nestAccessControl.UseRoles({
    resource: "Leaderboard",
    action: "read",
    possession: "own",
  })
  async leaderboard(
    @graphql.Args() args: LeaderboardFindUniqueArgs
  ): Promise<Leaderboard | null> {
    const result = await this.service.leaderboard(args);
    if (result === null) {
      return null;
    }
    return result;
  }

  @common.UseInterceptors(AclValidateRequestInterceptor)
  @graphql.Mutation(() => Leaderboard)
  @nestAccessControl.UseRoles({
    resource: "Leaderboard",
    action: "create",
    possession: "any",
  })
  async createLeaderboard(
    @graphql.Args() args: CreateLeaderboardArgs
  ): Promise<Leaderboard> {
    return await this.service.createLeaderboard({
      ...args,
      data: {
        ...args.data,

        user: args.data.user
          ? {
              connect: args.data.user,
            }
          : undefined,
      },
    });
  }

  @common.UseInterceptors(AclValidateRequestInterceptor)
  @graphql.Mutation(() => Leaderboard)
  @nestAccessControl.UseRoles({
    resource: "Leaderboard",
    action: "update",
    possession: "any",
  })
  async updateLeaderboard(
    @graphql.Args() args: UpdateLeaderboardArgs
  ): Promise<Leaderboard | null> {
    try {
      return await this.service.updateLeaderboard({
        ...args,
        data: {
          ...args.data,

          user: args.data.user
            ? {
                connect: args.data.user,
              }
            : undefined,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new GraphQLError(
          `No resource was found for ${JSON.stringify(args.where)}`
        );
      }
      throw error;
    }
  }

  @graphql.Mutation(() => Leaderboard)
  @nestAccessControl.UseRoles({
    resource: "Leaderboard",
    action: "delete",
    possession: "any",
  })
  async deleteLeaderboard(
    @graphql.Args() args: DeleteLeaderboardArgs
  ): Promise<Leaderboard | null> {
    try {
      return await this.service.deleteLeaderboard(args);
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new GraphQLError(
          `No resource was found for ${JSON.stringify(args.where)}`
        );
      }
      throw error;
    }
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @graphql.ResolveField(() => User, {
    nullable: true,
    name: "user",
  })
  @nestAccessControl.UseRoles({
    resource: "User",
    action: "read",
    possession: "any",
  })
  async getUser(@graphql.Parent() parent: Leaderboard): Promise<User | null> {
    const result = await this.service.getUser(parent.id);

    if (!result) {
      return null;
    }
    return result;
  }
}
